# Generated by Django 4.0.1 on 2022-05-26 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.IntegerField(max_length=14)),
                ('telefone', models.IntegerField(max_length=11)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
