# Generated by Django 4.0.1 on 2022-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_alter_fornecedor_cnpj_alter_fornecedor_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='Fornecedor',
        ),
    ]
