# Generated by Django 4.0.1 on 2022-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_alter_fornecedor_options_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True, 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
