# Generated by Django 4.0.1 on 2022-05-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0007_alter_fornecedor_cnpj_alter_fornecedor_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='arquivos-csv')),
                ('data_importacao', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Csv',
            },
        ),
    ]
