# Generated by Django 4.0.1 on 2022-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0011_alter_fornecedor_cnpj_alter_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(db_column='cnpj', max_length=18),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(db_column='nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(db_column='telefone', max_length=14),
        ),
    ]
