# Generated by Django 4.0.1 on 2022-05-29 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0012_alter_fornecedor_cnpj_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
