# Generated by Django 4.0.1 on 2022-05-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0014_alter_fornecedor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
