# Generated by Django 4.0.1 on 2022-05-26 19:14

from django.db import migrations, models
import fornecedor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_Fiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('numero_da_conta', models.CharField(max_length=10)),
                ('fornecedor', models.BooleanField(verbose_name=fornecedor.models.Fornecedor)),
                ('data_emissao_not', models.DateTimeField(auto_now=True)),
                ('nome_produto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
