# Generated by Django 4.0.1 on 2022-05-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_alter_fornecedor_options_alter_fornecedor_id_and_more'),
        ('notafiscal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_fiscal',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.ManyToManyField(to='fornecedor.Fornecedor'),
        ),
    ]
