# Generated by Django 4.0.1 on 2022-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_remove_nota_fiscal_fornecedor_nota_fiscal_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_fiscal',
            name='fornecedor',
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='numero_da_conta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
