# Generated by Django 4.0.1 on 2022-05-26 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_alter_fornecedor_options_alter_fornecedor_cnpj_and_more'),
        ('notafiscal', '0003_remove_nota_fiscal_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.ManyToManyField(to='fornecedor.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='categoria',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='nome_produto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='numero_da_conta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
