# Generated by Django 4.0.1 on 2022-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0005_alter_nota_fiscal_options_alter_nota_fiscal_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota_fiscal',
            options={'managed': True, 'verbose_name': 'Nota_Fiscal', 'verbose_name_plural': 'Notas_Fiscais'},
        ),
    ]
