# Generated by Django 4.0.1 on 2022-05-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0006_alter_nota_fiscal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='notas-csv')),
                ('data_importacao', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Csv_notas',
            },
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='data_emissao_not',
            new_name='data_emissao_nota',
        ),
    ]
