# Generated by Django 4.0.1 on 2022-05-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0007_csv_notas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='numero_da_conta',
            new_name='numero_da_nota',
        ),
    ]
