# Generated by Django 4.0.1 on 2022-05-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0011_alter_fornecedor_cnpj_alter_fornecedor_id_and_more'),
        ('notafiscal', '0008_rename_numero_da_conta_nota_fiscal_numero_da_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_fiscal',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
            preserve_default=False,
        ),
    ]
