# Generated by Django 4.0.1 on 2022-05-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0009_remove_nota_fiscal_fornecedor_nota_fiscal_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='data_emissao_nota',
            field=models.DateField(auto_now=True),
        ),
    ]
