# Generated by Django 4.0.1 on 2022-05-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0012_alter_nota_fiscal_data_emissao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='data_emissao_nota',
            field=models.DateField(default='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.CharField(max_length=100),
        ),
    ]
