# Generated by Django 4.0.1 on 2022-05-31 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0013_alter_nota_fiscal_data_emissao_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
