# Generated by Django 4.0.1 on 2022-05-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0015_alter_fornecedor_options'),
        ('notafiscal', '0014_alter_nota_fiscal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.ForeignKey(db_column='fornecedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
    ]
