# Generated by Django 4.0.1 on 2022-06-01 00:37

from django.db import migrations, models
import fornecedor.models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0016_alter_nota_fiscal_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.CharField(db_column='fornecedor', max_length=100, null=True, verbose_name=fornecedor.models.Fornecedor),
        ),
    ]
