# Generated by Django 4.0.1 on 2022-06-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0019_alter_nota_fiscal_data_emissao_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='fornecedor',
            field=models.CharField(db_column='fornecedor', max_length=100, null=True),
        ),
    ]
