# Generated by Django 4.0.1 on 2022-05-26 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notafiscal', '0004_nota_fiscal_fornecedor_alter_nota_fiscal_categoria_and_more'),
        ('fornecedor', '0005_alter_fornecedor_options_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas_Pagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('Fornecedor', models.ManyToManyField(to='fornecedor.Fornecedor')),
                ('ids_notas_fiscais', models.ManyToManyField(to='notafiscal.Nota_Fiscal')),
            ],
        ),
    ]
