# Generated by Django 4.0.1 on 2022-05-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas_pagar',
            options={'verbose_name': 'Contas_Pagar', 'verbose_name_plural': 'Contas_Pagar'},
        ),
        migrations.AlterModelTable(
            name='contas_pagar',
            table='Contas_Pagar',
        ),
    ]
