# Generated by Django 4.0.1 on 2022-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0002_alter_contas_pagar_options_alter_contas_pagar_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas_pagar',
            options={'managed': True, 'verbose_name': 'Contas_Pagar', 'verbose_name_plural': 'Contas_Pagar'},
        ),
    ]
