# Generated by Django 4.0.1 on 2022-05-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0003_alter_contas_pagar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas_pagar',
            options={'managed': True, 'verbose_name': 'Contas_pagar', 'verbose_name_plural': 'Contas_pagar'},
        ),
        migrations.AlterModelTable(
            name='contas_pagar',
            table='Contas_pagar',
        ),
    ]
