# Generated by Django 4.0.1 on 2022-05-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0013_alter_fornecedor_id'),
        ('contas_a_pagar', '0005_remove_contas_pagar_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_pagar',
            name='Fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
    ]
